CREATE TABLESPACE ToDo2 DATAFILE 'C:\Users\Carlos\Desktop\TableSpaceToDo\TODO2.ORA' SIZE 5M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE ToDo2TEMP TEMPFILE 'C:\Users\Carlos\Desktop\TableSpaceToDo\TODOTEMP2.ORA' SIZE 5M AUTOEXTEND ON;

DROP ROLE PerProyecto;
DROP ROLE DirProyecto;
DROP ROLE DirArea;
DROP ROLE Invitado;

DROP USER David CASCADE;
DROP USER Carlos CASCADE;
DROP USER Armando CASCADE;
DROP USER Pedro CASCADE;
DROP USER Catalina CASCADE;
DROP USER Miriam CASCADE;
DROP USER Luisa CASCADE;
DROP USER Camilo CASCADE;
DROP USER Jesus CASCADE;
DROP USER Juan CASCADE;
DROP USER Sergio CASCADE;
DROP USER Sandra CASCADE;


CREATE ROLE PerProyecto;
CREATE ROLE DirProyecto;
CREATE ROLE DirArea;
CREATE ROLE Invitado;


GRANT CONNECT, RESOURCE TO PerProyecto;
GRANT CONNECT, RESOURCE TO DirProyecto;
GRANT CONNECT, RESOURCE TO DirArea;
GRANT CONNECT, RESOURCE TO Invitado;


GRANT SELECT ANY TABLE TO DirProyecto;
GRANT UPDATE (ESTADOPRO), INSERT ON ADMINTODO.PROYECTO TO DirProyecto;
GRANT UPDATE (ESTADOEMP), INSERT ON ADMINTODO.EMPLEADO TO DirProyecto;
GRANT DELETE, INSERT ON ADMINTODO.AREA TO DirProyecto;
GRANT DELETE, INSERT ON ADMINTODO.TAREA TO DirProyecto;
GRANT EXECUTE ON ADMINTODO.FU_EMPPARTICIPACION TO DirProyecto; 
GRANT EXECUTE ON ADMINTODO.FU_PORCENTAJE_PROGRESO TO DirProyecto;


GRANT SELECT ANY TABLE TO DirArea;
GRANT UPDATE (ESTADOEMP), INSERT ON ADMINTODO.EMPLEADO TO DirArea;
GRANT UPDATE (ESTADOTAR), DELETE, INSERT ON ADMINTODO.TAREA TO DirArea;
GRANT EXECUTE ON ADMINTODO.FU_EMPPARTICIPACION TO DirArea;
GRANT EXECUTE ON ADMINTODO.FU_PORCENTAJE_PROGRESO TO DirArea;


GRANT SELECT ANY TABLE TO PerProyecto;
GRANT UPDATE (ESTADOTAR) ON ADMINTODO.TAREA TO PerProyecto;
GRANT EXECUTE ON ADMINTODO.FU_EMPPARTICIPACION TO PerProyecto;


GRANT SELECT ON ADMINTODO.EMPLEADO TO Invitado;
GRANT SELECT ON ADMINTODO.PROYECTO TO Invitado;


--DirProyecto

CREATE USER David IDENTIFIED BY d123 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT DIRPROYECTO TO David;
CREATE USER Carlos IDENTIFIED BY c123 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT DIRPROYECTO TO Carlos;

--DirArea
CREATE USER Armando IDENTIFIED BY a123 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT DIRAREA TO ARMANDO;
CREATE USER Pedro IDENTIFIED BY p123 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT DIRAREA TO PEDRO;
CREATE USER Catalina IDENTIFIED BY c456 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT DIRAREA TO CATALINA;

--PerProyecto
CREATE USER Miriam IDENTIFIED BY m123 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT PERPROYECTO TO MIRIAM;
CREATE USER Luisa IDENTIFIED BY l123 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT PERPROYECTO TO LUISA;
CREATE USER Camilo IDENTIFIED BY c124 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT PERPROYECTO TO CAMILO;
CREATE USER Jesus IDENTIFIED BY j453 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT PERPROYECTO TO JESUS;


--Invitado
CREATE USER Juan IDENTIFIED BY j123 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT INVITADO TO JUAN;
CREATE USER Sergio IDENTIFIED BY s123 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT INVITADO TO SERGIO;
CREATE USER Sandra IDENTIFIED BY s456 DEFAULT TABLESPACE ToDo2 TEMPORARY TABLESPACE ToDo2TEMP QUOTA 2 M ON ToDo2;
GRANT INVITADO TO SANDRA;



