CREATE TABLESPACE ToDo DATAFILE 'C:\Users\Carlos\Desktop\TableSpaceToDo\TODO.ORA' SIZE 5M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE ToDoTEMP TEMPFILE 'C:\Users\Carlos\Desktop\TableSpaceToDo\TODOTEMP.ORA' SIZE 5M AUTOEXTEND ON;

CREATE USER AdminToDo IDENTIFIED BY atd1 DEFAULT TABLESPACE ToDo TEMPORARY TABLESPACE ToDoTEMP QUOTA 2 M ON ToDO;

GRANT CONNECT TO AdminToDo;
GRANT ALL PRIVILEGE TO AdminToDo;